version: "3.9"
services:
  client-react-vite:
    image: client-react-vite
    build:
      context: client-react/
      dockerfile: Dockerfile.dev
    init: true
    volumes:
      # Bind entire sourcecode (for hot-reloading)
      - type: bind
        source: ./client-react
        target: /usr/src/app/
      # Add type=volume with no source and  only a target=node_modules
      #  so efectively overides the above bind mount for this path so node_modules wont be included
      - type: volume
        target: /usr/src/app/node_modules
      # Bind vite.config since file name is not default
      - type: bind
        source: ./client-react/vite.config.js
        target: /usr/src/app/vite.config.dev.js
    networks:
      - frontend
    ports:
      - 5173:5173
  client-react-nginx:
    image: client-react-nginx
    build:
      context: client-react/
      dockerfile: Dockerfile
    init: true
    networks:
      - frontend
    ports:
      - 80:8080
    restart: unless-stopped
  api-node:
    image: api-node
    build:
      context: api-node/
      dockerfile: Dockerfile
      # Would target production as the final stage but we want dev!
      target: dev
    init: true
    volumes:
      # Bind entire sourcecode (for hot-reloading)
      - type: bind
        source: ./api-node
        target: /usr/src/app/
      # Add type=volume with no source and only a target=node_modules
      #  so efectively overides the above bind mount for this path so node_modules wont be included
      - type: volume
        target: /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped
  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  frontend:
  backend:
